name: eog
adopt-info: eog
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core24

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/libpeas-1.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/libpeas-1.0
  /usr/lib/$CRAFT_ARCH_TRIPLET/eog:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/eog
  /usr/share/eog:
    bind: $SNAP/usr/share/eog

slots:
  # for GtkApplication registration
  eog:
    interface: dbus
    bus: session
    name: org.gnome.eog

apps:
  eog:
    common-id: org.gnome.eog.desktop
    command: usr/bin/eog
    extensions: [gnome]
    plugs:
      - home
      - gsettings
      - network
      - mount-observe
      - removable-media
    environment:
      LD_LIBRARY_PATH: :$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/eog:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/eog
      GI_TYPELIB_PATH: $SNAP/usr/lib/eog/girepository-1.0:$SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages

parts:
  eog:
    source: https://gitlab.gnome.org/GNOME/eog.git
    source-type: git
    source-tag: '45.3'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '46'
#     no-9x-revisions: true
    parse-info: [usr/share/metainfo/eog.appdata.xml]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dintrospection=true
      - -Dlibportal=false
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.eog$|=${SNAP}/meta/gui/org.gnome.eog.svg|g' $CRAFT_PART_SRC/data/org.gnome.eog.desktop.in.in
      sed -i.bak -e 's|media: media,|media: media, symlink_media: false,|g' $CRAFT_PART_SRC/help/meson.build
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/scalable/apps/org.gnome.eog.svg $CRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - libexempi-dev
      - libexif-dev
      - libjpeg-dev
      - liblcms2-dev
      - zlib1g-dev
      - python3-distutils
      - libsystemd-dev
    build-environment:
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/usr/share:$XDG_DATA_DIRS

  libraries:
    after: [eog]
    plugin: nil
    stage-packages:
      - libexif12
      - libexempi8
    prime:
      - "usr/lib/*/libexif*"
      - "usr/lib/*/libexempi*"

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [libraries]
    plugin: nil
    build-snaps: [core24, gtk-common-themes, gnome-46-2404]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
